### ISSUE TITLE
Is it possible to extend this parser to include custom DSL-like syntax?

### ISSUE THREAD

**Issue by springcomp** [mhutch/MonoDevelop.Xml#84]
I would like to be able to parse DSL languages that piggy-back on XML.
One of these lives in [Azure API Management XML policies](https://learn.microsoft.com/en-us/azure/api-management/api-management-policy-expressions).

One example would look like:

```xml
<policies>
  <inbound>
    <set-variable name="addition" value="@( 1 + 1 )" />
    <set-variable name="constant" value="@( "hello, world" )" />
    <set-variable name="indirect" value="@( context.Variables.GetValueOrDefault<string>("constant", "n/a") )" />
    <base />
  </inbound>
</policies>
```
You can see that the policy is no longer a valid XML file as it includes C# statements enclosed within `@( … )` delimiters inside attributes.
My assumption is that, instead of producing an invalid syntax, new syntax nodes would be attached to the AST.

Is it possible to extend this project to host custom syntax nodes at specific places ?

I figure I would need to slightly change the code and add a `XAttributeValue` node instead of the default assumption that attribute are always strings ?

**Comment by mhutch** [comment]
Yes, absolutely. The reason for the extensibility model was that the parser originally supported ASP.NET WebForms and HTML via custom parser states.

You can find the original ASP.NET WebForms states here: https://github.com/mono/monodevelop/tree/main/main/src/addins/AspNet/WebForms/Parser. Probably the most relevant one is `WebFormsAttributeValueState`, which is used to [replace the standard attribute value state](https://github.com/mono/monodevelop/blob/main/main/src/addins/AspNet/WebForms/Parser/WebFormsRootState.cs#L43). Note that these may be a bit out of date relative to this repository.

In [MonoDevelop.MSBuildEditor](https://github.com/mhutch/MonoDevelop.MSBuild), which has embedded expressions with a similar `@()` syntax, I don't use custom parser states, and instead parse the MSBuild expressions in a separate phase and wrap the XML DOM with a higher level MSBuild DOM. This is mostly due to how the MSBuild editor codebase evolved. and in hindsight I probably should have used custom parser states - though I would also have needed to update MonoDevelop.Xml to capture `XmlText` nodes in the DOM, as it does not currently do so.
